name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  pack-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish NuGet package
        uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: 'latest'

      - name: Pack project
        run: nuget pack .\template.nuspec -OutputDirectory ./nupkgs -Properties Configuration=Release
        
      - name: Publish project
        run: nuget push ./nupkgs/*.nupkg -src https://www.nuget.org/
